### ISSUE TITLE
AR300m button info

### ISSUE THREAD

**Issue by golf247** [jefferyto/openwrt-slide-switch#12]
new to Git, didn't know how to contact directly with this info.  I'm trying to contribute to this project.  I was working with this today with OpenWrt 18.06.2 r7676-cddd7b4c77.

My log is showing these buttons for AR300M.  switch-left pressed and switch-center pressed is what you want for this.
Sat Apr 13 22:40:47 2019 user.notice root: the button was BTN_1 and the action was released
Sat Apr 13 22:40:48 2019 user.notice root: the button was switch-left and the action was released
Sat Apr 13 22:40:48 2019 user.notice root: the button was switch-center and the action was pressed
Sat Apr 13 22:40:51 2019 user.notice root: the button was BTN_1 and the action was pressed
Sat Apr 13 22:40:52 2019 user.notice root: the button was switch-center and the action was released
Sat Apr 13 22:40:52 2019 user.notice root: the button was switch-left and the action was pressed

**Comment by jefferyto** [comment]
Hi, not really sure I understand your issue... Are you saying switch-left and switch-center are inverted?

**Comment by golf247** [comment]
No, I was just passing on the information to verify for the 300m router. These were from my log after setting up slide switch.
It's not an issue, I just didn't know how to contact the author in git.
Slowly learning...

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by jefferyto** [comment]
I see - opening an issue is fine. So you are saying the package is working correctly for your router (GL-AR300M)?

**Comment by golf247** [comment]
Correct.   Took me a little time to realize to put the openwrt button code into the 50-slider file but yes, it is working using the 'pressed' on slide left and center.
If you need me to, I can pop the case and confirm the third location is right, let me know and I'll do it tonight.  (Morning where I'm at).

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by golf247** [comment]
I verified the switch-right tonight.  Here's the log outputs moving the slide through the three different positions.  Again, this is for the AR300M running openwrt 18.06 (not the GLinet version) but I assume the switch buttons would be called the same on the GLinet firmware.
 

Mon Apr 15 18:25:43 2019 user.notice root: the button was BTN_0 and the action was pressed
Mon Apr 15 18:25:44 2019 user.notice root: the button was switch-center and the action was released
Mon Apr 15 18:25:44 2019 user.notice root: the button was switch-right and the action was pressed

Mon Apr 15 18:27:08 2019 user.notice root: the button was BTN_0 and the action was released
Mon Apr 15 18:27:10 2019 user.notice root: the button was switch-right and the action was released
Mon Apr 15 18:27:10 2019 user.notice root: the button was switch-center and the action was pressed

Mon Apr 15 18:27:43 2019 user.notice root: the button was BTN_1 and the action was pressed
Mon Apr 15 18:27:44 2019 user.notice root: the button was switch-center and the action was released
Mon Apr 15 18:27:44 2019 user.notice root: the button was switch-left and the action was pressed

Mon Apr 15 18:28:20 2019 user.notice root: the button was BTN_1 and the action was released
Mon Apr 15 18:28:21 2019 user.notice root: the button was switch-left and the action was released
Mon Apr 15 18:28:21 2019 user.notice root: the button was switch-center and the action was pressed

**Comment by jefferyto** [comment]
Thanks for your help :smile:

If you want, you can try updating the readme and submitting a pull request, either by [editing locally on your computer](https://akrabat.com/the-beginners-guide-to-contributing-to-a-github-project/) or [editing the file online](https://help.github.com/en/articles/editing-files-in-another-users-repository). If not, that's okay too; I'll probably get around to it later this week.

**Comment by golf247** [comment]
Keep it open and I'll look into doing this by the wkend.  (Or I'll let you know of I fail miserably.)  :)

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by jefferyto** [comment]
Thanks again for your help!
