### ISSUE TITLE
No button trigger on startup

### ISSUE THREAD

**Issue by flipreverse** [jefferyto/openwrt-slide-switch#14]
Hi!

First of all, slide-switch basically works for the AR750s. :)
However, there are two minor issues.
First, slide-switch does not emulate a button press/release on startup. According to my observations, it checks if the state file exists. If so, it does nothing. Just in case the state file does *not* exit, it emulate a button press.
This, however, is not what I expect slide-switch to do according to its documentation: 
> On boot, slide-switch will also trigger a button press for the active position of each switch.

Second, the board names in `switch-data.json` do not include the entire name. They, for example, just include gl-ar750s.
As far as I know all or at least most of the GL.iNet devices have a prefix, i.e.: `glinet,`.

Regards,
Alex

**Comment by jefferyto** [comment]
> First, slide-switch does not emulate a button press/release on startup. According to my observations, it checks if the state file exists. If so, it does nothing. Just in case the state file does not exit, it emulate a button press.

The state file(s) is stored in `/tmp` and on most OpenWrt systems this is tmpfs, so it is destroyed on shutdown. Is your `/tmp` stored on disk?

If you added `force` to the init command line inside `/etc/init.d/zzz-slide-switch` (so it becomes `/usr/sbin/slide-switch init force`), does that work for you?

> Second, the board names in switch-data.json do not include the entire name. They, for example, just include gl-ar750s.

Are you using an ar71xx or ath79 build of OpenWrt?

The script reads your device's board name from `/tmp/sysinfo/board_name`. Does yours contain `gl-ar750s` or `glinet,gl-ar750s` (or something else)?

**Comment by jefferyto** [comment]
Also would help to know what version of OpenWrt you are using.

**Comment by flipreverse** [comment]
> > First, slide-switch does not emulate a button press/release on startup. According to my observations, it checks if the state file exists. If so, it does nothing. Just in case the state file does not exit, it emulate a button press.
> 
> The state file(s) is stored in `/tmp` and on most OpenWrt systems this is tmpfs, so it is destroyed on shutdown. Is your `/tmp` stored on disk?
Unfortunately, yes. For some reason the state file is stored in `/slide-switch`. I assume it should be `/tmp/slide-switch`.
> 
> If you added `force` to the init command line inside `/etc/init.d/zzz-slide-switch` (so it becomes `/usr/sbin/slide-switch init force`), does that work for you?
Yes.
> 
> > Second, the board names in switch-data.json do not include the entire name. They, for example, just include gl-ar750s.
> 
> Are you using an ar71xx or ath79 build of OpenWrt?
ath79
> 
> The script reads your device's board name from `/tmp/sysinfo/board_name`. Does yours contain `gl-ar750s` or `glinet,gl-ar750s` (or something else)?
It contains `glinet,gl-ar750s`.

I'm currently using my own version of OpenWRT since the nand support for the ar750s is still not merged. My branch uses OpenWRT commit 12840674d0550e6f5aa077cd2b578988f0c07074.

**Comment by jefferyto** [comment]
> Unfortunately, yes. For some reason the state file is stored in `/slide-switch`. I assume it should be `/tmp/slide-switch`.

Then this is real reason why it isn't initializing properly on boot, it should be in `/tmp`.

I assume you built the slide-switch .ipk package (either using the sdk or from master) or installed a pre-built snapshot package, and didn't download the source files from here and manually copied it onto your device?

> > Are you using an ar71xx or ath79 build of OpenWrt?

> ath79

I haven't added ath79 device names to the switch data yet; what is there now are ar71xx names. Thanks for reminding me :+1:

**Comment by flipreverse** [comment]
> I assume you built the slide-switch .ipk package (either using the sdk or from master) or installed a pre-built snapshot package, and didn't download the source files from here and manually copied it onto your device?

I build the ipk package from master, and directly include it in my sysupgrade image.
> I haven't added ath79 device names to the switch data yet; what is there now are ar71xx names. Thanks for reminding me 👍

ah. No problem. :)

**Comment by flipreverse** [comment]
`@runstatedir@` seems to be empty: https://github.com/jefferyto/openwrt-slide-switch/blob/b900efe8c71b5f1ab2289b5d3e27d7a3765ba9fb/src/usr/share/slide-switch/functions.sh-cut#L32

**Comment by jefferyto** [comment]
Hmm that should have defaulted to `[localstatedir]/run` :thinking:

**Comment by flipreverse** [comment]
My `functions.sh` say `run_dir=/slide-switch`. :-(

**Comment by jefferyto** [comment]
Both of these should be fixed in 0.9.5 (just tagged) - please reopen if there are more issues.

Thanks again!
