### ISSUE TITLE
Improve documentation: Usage

### ISSUE THREAD

**Issue by BlessDeix92** [jefferyto/openwrt-slide-switch#16]
I just installed and learned about slide-switch for the first time. I found the Usage section of the README to be lacking. 

It would be nice to know that a "slide-switch init" or a reboot is needed to get things working. The arguments to this command are not documented. Would be great to have some simple text about what the "switch" and "position" arguments do.

**Comment by jefferyto** [comment]
Apologies for the delay. `slide-switch init` should automatically be run when you first install the package.

What version of OpenWrt are you using?

**Comment by jefferyto** [comment]
Closing due to age / lack of response.
