### ISSUE TITLE
GL.iNet GL-MT300A is verified

### ISSUE THREAD

**Issue by jackschmidt** [jefferyto/openwrt-slide-switch#17]
The GL-MT300A works, thank you! I used openwrt 19.07.3 with slide-switch 0.95 (from opkg).

It did not initially appear to work. I am not sure if it was a typo on my part or a longer initial delay. I spent quite some time debugging it, but I think the final configuration that works is the default.

Perhaps more direct instructions would help:

* To test what buttons are pushed, follow the ["preliminary steps"](/openwrt.org/docs/guide-user/hardware/hardware.button) on the OpenWRT wiki:

```
mkdir -p /etc/hotplug.d/button
 
cat << "EOF" > /etc/hotplug.d/button/buttons
logger "the button was ${BUTTON} and the action was ${ACTION}"
EOF
```
* The procd style button reactions are stored in `/etc/rc.button/` and must be made executable. For example, create an executable script `/etc/rc.button/switch-left` for the GL-MT300A and it will be triggered once on boot (assuming the slide is in the left position) and once whenever the slide moves away (`ACTION=released`) or back to the left (`ACTION=pressed`).

```
cat << "EOF" > /etc/rc.button/switch-left
logger "the button was ${BUTTON} and the action was ${ACTION}"
EOF
chmod 755 /etc/rc.button/switch-left
```

* Both `/etc/hotplug.d/button/*` and `/etc/rc.button/switch-left` will run when the slide switch is moved to or from the left position. The `BTN_0` and `BTN_1` button actions will also run.

**Comment by jefferyto** [comment]
Thanks - I would prefer not to duplicate information from the OpenWrt wiki; reading/understanding the push button page is required. There is also no need to "discover" button names; the readme describes how button names are derived and includes a table of switch and position names for this purpose.
