### ISSUE TITLE
Build instructions?

### ISSUE THREAD

**Issue by nickdademo** [jefferyto/openwrt-slide-switch#22]
I'm using the GL.iNet AR750S which has OpenWRT v19.07.8.

`opkg install slide-switch` seems to install the older version of this package: `0.9.5`

What is the best way to get `slide-switch 1.0.0` in this case? Do I need to build from source? Or is there a remote package URL with 1.0.0 that I can simply point `opkg` to?

Thanks!

**Comment by jefferyto** [comment]
0.9.6 and newer require at least OpenWrt 21.02, so even if you built a package for 1.0.0 it wouldn't work on your device.

0.9.5 should [support](https://github.com/jefferyto/openwrt-slide-switch/tree/0.9.5#supported-devices) the AR750S (although it wasn't verified with that version of the package).

I suggest looking into upgrading OpenWrt though; 19.07 is very old at this point.
