### ISSUE TITLE
Please provide release build packages for LEDE

### ISSUE THREAD

**Issue by lukeross** [jefferyto/openwrt-slide-switch#3]
The ar71xx package doesn't install cleanly on LEDE 17.01.1 because the architecture in opkg now seems to be called `mips_24kc`. Using `arch` overrides in /etc/opkg.conf allowed me to install it, and it seems to work fine once installed.

**Comment by jefferyto** [comment]
The package should be available from the official LEDE / OpenWrt packages feed. Not sure about LEDE 17.0.1.1, but I'm able to install it on my 17.01.4 device (`opkg install slide-switch`). Please reopen if it doesn't work.
