### ISSUE TITLE
ar71xx_board_name: not found

### ISSUE THREAD

**Issue by HelferP** [jefferyto/openwrt-slide-switch#4]
I added in ar71xx.json new model tl-wr902ac-v1, but after router reboot in the log I get the error /usr/sbin/slide-switch: /usr/lib/slide-switch/platform.sh: line 12: ar71xx_board_name: not found and slider not work.
PS If I specify the device name like this: `board_name="tl-wr902ac-v1"` then it works.

**Comment by jefferyto** [comment]
0.9.1 includes support for the tl-wr902ac-v1 (switch / position names in readme) and fixes the board name error. The updated package should be available in the development snapshots package feed :smile:
