### ISSUE TITLE
Support for TL-WR902AC V3

### ISSUE THREAD

**Issue by grantstephens** [jefferyto/openwrt-slide-switch#6]
Thank you for what looks like an awesome package. I just tried it on the V3 of TL-WR902AC but it does not seem to be functioning. The buttons script picks up BTN_0 and BTN_1, but I don't seem to get the mode-ap 'events'. How do I test it, or provide you with more details?

**Comment by jefferyto** [comment]
Thanks for trying! The package will need to be updated for the TL-WR902AC v3 :smile: 

Basically what is needed is the truth table for BTN_0 and BTN_1 (whether they are pressed or not) for each of the 3 slide switch positions. If you can share the contents of `/sys/kernel/debug/gpio` from your device, for each switch position, that would be great. (Or you can just record whether each "button" is `hi` or `lo`, I believe BTN_0 is gpio-2 and BTN-1 is gpio-3.)

If you want, you can also add the data to `src/usr/lib.ramips/ramips.json-cut` directly (it may be easiest to copy the JSON for tl-wr902ac-v1 from `/src/usr/lib.ar71xx/ar71xx.json-cut` and edit from there) and do a pull request :wink:

**Comment by Chuckame** [comment]
Hi,
Here is the gpio content corresponding to wanted switch : 
```
root@OpenWrt:~# cat /sys/kernel/debug/gpio
gpiochip0: GPIOs 0-31, parent: platform/10000600.gpio, 10000600.gpio:
 gpio-2   (                    |sw1                 ) in  hi
 gpio-3   (                    |sw2                 ) in  lo
```

Modes : 
- AP/Rng ext/Client : 
   - gpio-2 : hi
   - gpio-3 : hi
- Share hotspot : 
   - gpio-2 : hi
   - gpio-3 : lo
- Share eth : 
   - gpio-2 : lo
   - gpio-3 : hi

**Comment by jefferyto** [comment]
Thanks again @Chuckame for your help!

I've tagged 0.9.2 with support for this device, and I've submitted update PRs for [trunk](https://github.com/openwrt/packages/pull/6508) and [18.06](https://github.com/openwrt/packages/pull/6509), so hopefully you will be able to download/update the package using opkg soon.

**Comment by grantstephens** [comment]
Thank you @Chuckame and @jefferyto
