### ISSUE TITLE
Add support for HooToo TravelMate Nano

### ISSUE THREAD

**Issue by CGamesPlay** [jefferyto/openwrt-slide-switch#8]
I was able to add support for the HooToo TravelMate Nano by making a simple modification to the configuration file:

```
	"ht-tm02": {
		"mode": {
			"gpios": [ 14 ],
			"codes": [ "BTN_0" ],
			"positions": {
				"lo": "wired",
				"hi": "wireless"
			}
		}
	}
```

You can see on [page 4](https://www.hootoo.com/media/downloads/User%20Guide%201.0%20-%20HT-TM02%20TripMate%20Nano.pdf) that the switch doesn't have a very clear name, but the iconography is wired / wireless.

**Comment by jefferyto** [comment]
Thanks for this - would you mind opening a pull request? (I believe you will want to edit [src/usr/lib.ramips/ramips.json-cut](https://github.com/jefferyto/openwrt-slide-switch/blob/master/src/usr/lib.ramips/ramips.json-cut).) That way you get the credit in git history :laughing:
